// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PruebaLogan.MODEL.Entities;

namespace PruebaLogan.CONTEXT.Context;

public partial class TestLoganContext : DbContext
{
    public TestLoganContext(DbContextOptions<TestLoganContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserT> UserT { get; set; }

    public virtual DbSet<UserType> UserType { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserT>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserT__3214EC07FB94CE4D");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Clave)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Cuenta).IsRequired();
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.TipoUsuarioNavigation).WithMany(p => p.UserT)
                .HasForeignKey(d => d.TipoUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserT__TipoUsuar__267ABA7A");
        });

        modelBuilder.Entity<UserType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserType__3214EC0748E191F8");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(6);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(30);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}