// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PruebaLogan.MODEL.Entities;

public partial class UserT
{
    public Guid Id { get; set; }

    public string Clave { get; set; }

    public string Cuenta { get; set; }

    public Guid TipoUsuario { get; set; }

    public bool? Estado { get; set; }

    public string Nombre { get; set; }

    public virtual UserType TipoUsuarioNavigation { get; set; }
}