// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PruebaLogan.MODEL.Entities;

public partial class UserType
{
    public Guid Id { get; set; }

    public string Descripcion { get; set; }

    public string Codigo { get; set; }

    public virtual ICollection<UserT> UserT { get; set; } = new List<UserT>();
}